package viewPackage;

import java.util.ArrayList;
import java.util.Arrays;

public class ValiditePartiesDuCorps {
    ArrayList<String> partiesDuCorps;
    public ValiditePartiesDuCorps() {
        partiesDuCorps = new ArrayList<String>(Arrays.asList("Abdomen\n" +
                "Aisselles",
                "Aorte abdominale",
                "Aorte thoracique",
                "Appendice",
                "Aréole",
                "Artère fémorale",
                "Artère vertébrale",
                "Avant-bras",
                "Axis",
                "Barbe",
                "Bassin",
                "Biceps brachial",
                "Bioceps fémoral",
                "Bouche",
                "Bras",
                "Bulbe rachidien",
                "Caecum",
                "Cage thoracique",
                "Calcanéum",
                "Canine",
                "Ceinture pelvienne",
                "Cerveau",
                "Cervelet",
                "Cheveux",
                "Cheville",
                "Chiasma optique",
                "Cils",
                "Clavicule",
                "Coccyx",
                "Coeur",
                "Col de l'utérus",
                "Col du fémur",
                "Colonne vertébrale",
                "Cordes vocales",
                "Corps calleux",
                "Cou",
                "Coude",
                "Crête iliaque",
                "Cubitus",
                "Cuisse",
                "Dent",
                "Diaphragme",
                "Disque intervertébral",
                "Doigt",
                "Dos",
                "Duodénum",
                "Dure-mère",
                "Encéphale",
                "Epaule",
                "Epididyme",
                "Epiphyse",
                "Estomac",
                "Épiglotte",
                "Fémur",
                "Fesses",
                "Flore intestinale",
                "Foie",
                "Follicule ovarien",
                "Fornix",
                "Front",
                "Fundus",
                "Genou",
                "Glande de Cowper",
                "Glande surrénale",
                "Grand trochanter",
                "Gros intestin",
                "Hanche",
                "Hélix",
                "Hématies",
                "Humérus",
                "Hymen",
                "Hypophyse",
                "Hypothalamus",
                "Iléon",
                "Ilion",
                "Incisive",
                "Intestin grêle",
                "Iris",
                "Ischion",
                "Jambe",
                "Langue",
                "Larynx",
                "Leucocytes",
                "Ligament croisé antérieur",
                "Ligament inguinal",
                "Ligne blanche",
                "Lobe de l'oreille",
                "Lobe frontal",
                "Lobe occipital",
                "Lobe pariétal",
                "Lobe temporal",
                "Luette",
                "Lymphocytes",
                "Main",
                "Mandibule",
                "Manubrium",
                "Maxillaire",
                "Membre inférieur",
                "Menton",
                "Mésencéphale",
                "Métacarpes",
                "Métatarse",
                "Moelle épinière",
                "Molaires",
                "Mollet",
                "Muscle gastrocnémien",
                "Muscle Grand Dorsal",
                "Muscle Petit Rond",
                "Muscle Soléaire",
                "Muscle Trapèze",
                "Myocarde",
                "Nerf facial",
                "Nerf fémoral",
                "Nerf médian",
                "Nerf optique",
                "Nerf phrénique",
                "Nerf pudendal",
                "Nerf radial",
                "Nerf trijumeau",
                "Nerf ulnaire",
                "Nerf vague",
                "Nez",
                "Nombril",
                "Nuque",
                "Oeil",
                "Oesophage",
                "Omoplate",
                "Ongle",
                "Oreille",
                "Oropharynx",
                "Orteils",
                "Os de la main",
                "Os hyoïde",
                "Os naviculaire",
                "Os occipital",
                "Os palatin",
                "Os temporal",
                "Os zygomatique",
                "Ovaire",
                "Patte",
                "Pancréas",
                "Paume de la main",
                "Peau",
                "Pénis",
                "Péricarde",
                "péritoine",
                "Péroné",
                "Petites lèvres",
                "Pharynx",
                "Pied",
                "Plexus brachial",
                "Poignet",
                "Poils pubiens",
                "Pouce",
                "Poumons anatomie",
                "Prémolaires",
                "Pubis",
                "Pupille",
                "Pylore",
                "Radius",
                "Rate",
                "Rectum",
                "Rein",
                "Rotule",
                "Sacrum",
                "Sartorius",
                "Scrotum",
                "Sein",
                "Sinus coronaire",
                "Sourcil",
                "Sternum",
                "Symphyse pubienne",
                "Système lymphatique",
                "Talon",
                "Tarse",
                "Tempe",
                "Tendon d'Achille",
                "Testicule",
                "Thalamus",
                "Thorax",
                "Tibia",
                "Trachée",
                "Tragus",
                "Triceps brachial",
                "Trompes de Fallope",
                "Tronc",
                "Tronc cérébral",
                "Tronc coeliaque",
                "Uretère",
                "Utérus",
                "Vagin",
                "Vaisseau sanguin",
                "Valve aortique",
                "Valve mitrale",
                "Valve tricuspide",
                "Veine azygos",
                "Veine cave inférieure",
                "Ventricule gauche",
                "Vertèbre cervicale",
                "Vertèbres lombaires",
                "Vésicule biliaire",
                "Vésicule séminale",
                "Vessie",
                "Vomer"));
    }
}

/*


 */
